# EDA

In [1]:
import pandas as pd

In [13]:
import os
print(os.getcwd())

c:\Users\fanss\OneDrive\Documents\Brain Code Camp\ds003458\Project

In [18]:
df = pd.read_excel(r'C:\Users\fanss\OneDrive\Documents\Brain Code Camp\ds003458\code\Bandit Tracking _ For Upload.xlsx')
df

     ID  Perform  Peripherals  EMG OK  SCR OK  Bandit Duration  Sex  Age
0   102        1            0       0       0             24.0    1   20
1   103        1            0       0       0             28.0    2   18
2   201        1            0       0       0             29.0    1   20
3   208        1            1       1       1             27.0    2   18
4   209        1            1       0       1             50.0    2   21
5   210        1            1       1       1              NaN    2   19
6   213        1            1       1       1             36.0    2   19
7   214        1            1       1       1             37.0    2   20
8   215        1            0       0       0             40.0    1   19
9   216        1            1       1       1             53.0    2   21
10  220        1            1       0       0             50.0    2   19
11  221        1            1       1       1             35.0    2   19
12  223        1            1       1       1             40.0    2   18
13  224        1            1       1       1             32.0    1   23
14  225        1            1       1       1             35.0    1   21
15  226        1            1       1       1             33.0    1   22
16  227        1            1       1       1             38.0    2   19
17  228        1            1       1       1             41.0    1   22
18  230        1            1       1       1             68.0    2   24
19  231        1            1       1       1             38.0    2   19
20  232        1            1       1       1             40.0    2   19
21  234        1            1       0       1             35.0    2   20
22  235        1            1       1       1             40.0    2   19

- Sex

In [20]:
gender_counts = df['Sex'].value_counts()
print(f"Male: {gender_counts[1]}")
print(f"Female: {gender_counts[2]}")

Male: 7
Female: 16

- Age

In [21]:
min_age = df['Age'].min()
max_age = df['Age'].max()
average_age = df['Age'].mean()

In [23]:
print(f"Min Age: {min_age}")
print(f"Max Age: {max_age}")
print(f"Avg Age: {round(average_age, 2)}")

Min Age: 18
Max Age: 24
Avg Age: 19.96